# Generated by Django 4.2.5 on 2023-09-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AImodel', '0002_alter_producto_info_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tiendaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AImodel.tienda'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='empresaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AImodel.empresa'),
        ),
    ]
