USE QuickMerkDB
GO

/****** Object:  Table [dbo].[tipo_Documentos]    Script Date: 16/07/2023 4:27:02 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tipo_Documentos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TipoDeDocumento] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_tipo_Documentos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

