USE [Peopledb]
GO

/****** Object:  Table [dbo].[tipo_Cuentas]    Script Date: 16/07/2023 4:26:50 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tipo_Cuentas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[tipo_cuenta] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_tipo_Cuentas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

